#
   name: Déploiement Conditionnel
   
   # Déclenchement manuel avec paramètres d'entrée pour plus de contrôle
   on:
     workflow_dispatch:
       inputs:
         environment:
           description: 'Environnement de déploiement'
           required: true
           default: 'staging'
           type: choice
           options:
           - staging
           - production
   
   jobs:
     validation:
       runs-on: ubuntu-latest
       steps:
       - name: Vérifications
         run: |
           echo "Validation des prérequis"
           echo "Environnement choisi: ${{ github.event.inputs.environment }}"
     
     deploy:
       runs-on: ubuntu-latest
       needs: validation
       environment: ${{ github.event.inputs.environment }}
       
       steps:
       - name: Déploiement
         run: |
           echo "🚀 Déploiement vers ${{ github.event.inputs.environment }}"
           
           if [ "${{ github.event.inputs.environment }}" == "production" ]; then
             echo "🔒 Déploiement PRODUCTION - vérifications renforcées"
           else
             echo "🟡 Déploiement STAGING - environnement de test"
           fi
       
       - name: Notification
         if: always()
         run: |
           if [ "${{ job.status }}" == "success" ]; then
             echo "✅ Déploiement réussi"
           else
             echo "❌ Échec du déploiement"
           fi
